name: Main

on:
  push:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: main
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rafaelmartins/cmake-stm32-firmware-release/actions/setup@main
      - uses: rafaelmartins/cmake-stm32-firmware-release/actions/build@main
        with:
          source: firmware

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: rafaelmartins/cmake-stm32-firmware-release/actions/deploy@main
